name: ZeroSSL
on:
  schedule:
    - cron: '10 9 * * 5'
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/ZeroSSL.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/ZeroSSL.yml'



concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true



jobs:
  ZeroSSL:
    runs-on: ubuntu-latest
    env:
      TEST_ACME_Server: "ZeroSSL.com"
      CA_ECDSA: "ZeroSSL ECC Domain Secure Site CA"
      CA: "ZeroSSL RSA Domain Secure Site CA"
      CA_EMAIL: "githubtest@acme.sh"
      TEST_PREFERRED_CHAIN: ""
      QUICK_TEST: 1
    steps:
    - uses: actions/checkout@v4
    - name: Run Test
      run: |
          sudo apt-get update && sudo apt-get install -y curl socat && \
          cd ../acmetest && sudo --preserve-env ./letest.sh


